# Generated by Django 5.1.7 on 2025-04-01 12:26

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('items', 'ItemCategory')
    categories = [
        'Stationary', 'Furniture', 'Clothing', 
        'Electronics', 'Home', 'Kitchen', 'Vehicles'
    ]

    for name in categories:
        Category.objects.create(name=name)



def remove_categories(apps, schema_editor):
    Category = apps.get_model('items', 'ItemCategory')

    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories)
    ]
