# Generated by Django 5.1.7 on 2025-04-01 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_create_initial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['location'], name='items_items_locatio_72fd93_idx'),
        ),
    ]
