# Generated by Django 5.1.7 on 2025-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_items_image_remove_items_image_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('free', 'Free')], default='sell', max_length=5),
        ),
    ]
