# Generated by Django 5.1.7 on 2025-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_items_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
