# Generated by Django 5.1.7 on 2025-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
